package com.ucs.cctv.Pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * MonitorGroup generated by hbm2java
 */
public class MonitorGroup implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer groupId;
	private String groupName;
	private String remark;
	
	private Set<CameraInfo> cameraMerbers = new HashSet<CameraInfo>();
	private Set<OperatorInfo> operators;

	public MonitorGroup() {
	}

	public MonitorGroup(String groupName, String remark) {
		this.groupName = groupName;
		this.remark = remark;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<CameraInfo> getCameraMerbers() {
		return cameraMerbers;
	}

	public void setCameraMerbers(Set<CameraInfo> cameraMembers1) {
		this.cameraMerbers = cameraMembers1;
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Set<OperatorInfo> getOperators() {
		return operators;
	}

	public void setOperators(Set<OperatorInfo> operators) {
		this.operators = operators;
	}

}
